version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.0-jammy
  run-test:
    machine: true
    resource_class: moneyforwardvietnam/qa-runner

    steps:
      - node/install
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Playwright browser install
          command: npx playwright install --with-deps
      - run:
          name: Playwright exec
          command: npx playwright test --config=./playwright.config.ts
      - store_artifacts:
          path: ./playwright-report
          destination: playwright-report-first
workflows:
  run_e2e_test:
    jobs:
      - run-test:
          filters:
            branches:
              only: ARM-6546-CommonFunction-CircleCI-integration