version: 2.1

orbs:
  node: circleci/node@5.1.0
  jq: circleci/jq@2.2.0  

jobs:
  run-test:
    machine: true
    resource_class: moneyforwardvietnam/qa-runner

    steps:
      - node/install
      - checkout
      - jq/install
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Playwright browser install
          command: npx playwright install --with-deps
      - run:
          name: Install pip
          command: |
            python3 --version
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python3 get-pip.py
      - run:
          name: Install TestRail CLI
          command: python3 -m pip install trcli
      - run:
          name: Playwright exec
          command: npx playwright test --config=./playwright.config.ts
      - run:
          name: Generate Test Execution Date and Time
          command: |
            export CURRENT_DATE_TIME=$(date -d "9 hours" +'%Y-%m-%d %H:%M:%S')
            echo "Current Date and Time is = $CURRENT_DATE_TIME"
            echo "export REPORT_GENERATED_DATE=\"$CURRENT_DATE_TIME\" " >> $BASH_ENV
      - run:
          name: Upload Report to Test Rail
          command: |
            echo "Uploading Report to Test Rail"
            source "$BASH_ENV"
            echo "Project: $PROJECT"
            echo "Username: $TESTRAIL_USERNAME"
            echo "Report Date: $REPORT_GENERATED_DATE"
            echo "File Path: ./test-results/junit-report.xml"
            trcli -n -h "https://moneyforward.tmxtestrail.com" --project "ARM - Accounts Receivable Management" --username "alam.shakir@moneyforward.co.jp" --password "Info@1234" parse_junit --case-matcher "property" --title "Playwright Automated Test Run on $REPORT_GENERATED_DATE JST" -f "./test-results/junit-report.xml" --suite-name "Regression Test"
      - store_artifacts:
          path: ./playwright-report
          destination: playwright-report-first
workflows:
  version: 2
  run-e2e-test:
    triggers:
      - schedule:
          cron: "45 10 * * *"  # This cron expression runs the job daily at 10:45 AM UTC (4:15 PM IST)
          filters:
            branches:
              only:
                - ARM-6546-CommonFunction-CircleCI-integration
    jobs:
      - run-test:
          filters:
            branches:
              only: ARM-6546-CommonFunction-CircleCI-integration