version: 2.1

jobs:
  run-test:
    circleci_ip_ranges: true
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.0-jammy
    resource_class: medium

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Playwright browser install
          command: npx playwright install --with-deps
      - run:
          name: Playwright exec
          command: npx playwright test --config=./playwright.config.ts
      - store_artifacts:
          path: ./playwright-report
          destination: playwright-report-first
      - store_artifacts:
          path: /tmp/artifacts          
workflows:
  run_e2e_test:
    jobs:
      - run-test:
          filters:
            branches:
              only: ARM-6546-CommonFunction-CircleCI-integration